### ISSUE TITLE
Redux Devtools not working on deployed version

### ISSUE THREAD

**Issue by bitflower** [bfmatei/stencil-boilerplate#2]
**Version:**

**I'm submitting a:**

- [ x ] bug report
- [ ] feature request
- [ ] support request

**Current Behavior:**
The Redux Dev tools don't work on the deployed version of the app under:
https://stencil-boilerplate.bmatei.com/dashboard

Bug or feature !? I might be the noob among us here ;-)

**Expected Behavior:**
It works ;-)

**Steps to Reproduce:**
Go to https://stencil-boilerplate.bmatei.com/dashboard and open the DEV tools inside Chrome

**Comment by bfmatei** [comment]
Hey Max!

In order to activate Redux DevTools on prod builds, please adjust this line: https://github.com/bfmatei/stencil-boilerplate/blob/master/src/redux/store.ts#L11 to `} from 'redux-devtools-extension';`

As a best practice, Redux DevTools should be disabled during prod builds for a lil' bit of performance  but also to avoid data tampering. For example: using a Redux Forms plugin for a login form might leave the form data in the store after the process ends. A person can come and read this password extremely easy and fast (also giving the fact that the extension does not require browser reload).

**Comment by bitflower** [comment]
Oh, I'm such a Redux noob....

Closing and thanks for clarifying!
